name: Build SimpleVisor Driver

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Build Solution
      run: msbuild SimpleVisor.sln /p:Configuration=Release /p:Platform=x64

    - name: Upload driver artifact
      uses: actions/upload-artifact@v4
      with:
        name: SimpleVisor-driver
        path: bin\x64\Release\SimpleVisor.sys
    - name: Build Solution
      run: msbuild SimpleVisor.sln /p:Configuration=Release /p:Platform=x64 /verbosity:detailed
        
